<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Domain\ReadingPlans\Enums\FragmentType;
use App\Domain\ReadingPlans\Enums\ReadingPlanStatus;
use App\Domain\ReadingPlans\Models\ReadingPlan;
use App\Domain\ReadingPlans\Models\ReadingPlanDay;
use App\Domain\ReadingPlans\Models\ReadingPlanDayFragment;
use Database\Seeders\Concerns\ParsesPlanReferences;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Seeds the "5x5x5 New Testament Reading Plan" (Navigators Discipleship Tool):
 * read all 260 chapters of the New Testament 5 days a week, 5 minutes a day.
 * Weekend slots are reflection days, and the final day is a celebration.
 *
 * Idempotent: re-running updates plan metadata, deletes existing days and
 * fragments via cascade, and rebuilds them.
 */
final class FiveByFiveByFiveNewTestamentReadingPlanSeeder extends Seeder
{
    use ParsesPlanReferences;

    private const SLUG = '5x5x5-new-testament-reading-plan';

    private const REFLECTION_HTML = [
        'en' => '<p>Pause in your reading to dig into the Bible. Try one of these five ways to dig deeper:</p><ol><li>Underline or highlight key words or phrases.</li><li>Put it in your own words.</li><li>Ask and answer questions about the passage.</li><li>Capture the big idea.</li><li>Personalize the meaning — how could your life be different today?</li></ol>',
        'ro' => '<p>Fă o pauză din citire pentru a aprofunda Biblia. Încearcă una dintre aceste cinci metode:</p><ol><li>Subliniază sau evidențiază cuvinte sau expresii cheie.</li><li>Pune textul în propriile tale cuvinte.</li><li>Pune întrebări despre pasaj și răspunde la ele.</li><li>Surprinde ideea principală.</li><li>Personalizează mesajul — cum ar putea fi viața ta diferită astăzi?</li></ol>',
        'hu' => '<p>Tarts szünetet az olvasásban, hogy elmélyülj a Bibliában. Próbáld ki ezt az öt módszert a mélyebb megértéshez:</p><ol><li>Húzd alá vagy emeld ki a kulcsszavakat és kifejezéseket.</li><li>Fogalmazd meg a saját szavaiddal.</li><li>Tegyél fel kérdéseket a szakaszról és válaszolj rájuk.</li><li>Ragadd meg a fő gondolatot.</li><li>Tedd személyessé az üzenetet — mit változtathat ma az életeden?</li></ol>',
        'es' => '<p>Haz una pausa en tu lectura para profundizar en la Biblia. Prueba una de estas cinco formas de profundizar:</p><ol><li>Subraya o resalta palabras o frases clave.</li><li>Explícalo con tus propias palabras.</li><li>Haz preguntas sobre el pasaje y respóndelas.</li><li>Capta la idea principal.</li><li>Personaliza el mensaje — ¿cómo podría ser diferente tu vida hoy?</li></ol>',
        'fr' => "<p>Faites une pause dans votre lecture pour approfondir la Bible. Essayez l'une de ces cinq façons d'aller plus loin :</p><ol><li>Soulignez ou surlignez les mots-clés ou expressions importantes.</li><li>Reformulez le passage avec vos propres mots.</li><li>Posez des questions sur le passage et répondez-y.</li><li>Dégagez l'idée principale.</li><li>Personnalisez le message — en quoi votre vie pourrait-elle être différente aujourd'hui ?</li></ol>",
        'de' => '<p>Halte beim Lesen inne, um tiefer in die Bibel einzutauchen. Probiere eine dieser fünf Methoden:</p><ol><li>Unterstreiche oder markiere Schlüsselworte und -sätze.</li><li>Gib den Abschnitt in eigenen Worten wieder.</li><li>Stelle Fragen zum Abschnitt und beantworte sie.</li><li>Erfasse den Kerngedanken.</li><li>Personalisiere die Botschaft — wie könnte dein Leben heute anders sein?</li></ol>',
        'it' => "<p>Fai una pausa nella lettura per approfondire la Bibbia. Prova uno di questi cinque modi per andare più a fondo:</p><ol><li>Sottolinea o evidenzia parole o frasi chiave.</li><li>Riformula il brano con parole tue.</li><li>Fai domande sul testo e rispondi.</li><li>Cogli l'idea centrale.</li><li>Personalizza il messaggio — in che modo la tua vita potrebbe essere diversa oggi?</li></ol>",
    ];

    private const REJOICE_HTML = [
        'en' => "<p>Rejoice! You've completed the New Testament. Take time to celebrate what God has revealed and consider how the readings have shaped you over the past year.</p>",
        'ro' => '<p>Bucură-te! Ai parcurs întregul Nou Testament. Sărbătorește ce ți-a descoperit Dumnezeu și gândește-te cum te-au modelat aceste citiri în ultimul an.</p>',
        'hu' => '<p>Örvendezz! Végigolvastad az Újszövetséget. Szánj időt arra, hogy ünnepeld, amit Isten kijelentett, és gondold át, hogyan formáltak az olvasmányok az elmúlt évben.</p>',
        'es' => '<p>¡Alégrate! Has completado el Nuevo Testamento. Tómate un tiempo para celebrar lo que Dios ha revelado y reflexiona sobre cómo te han moldeado las lecturas durante este último año.</p>',
        'fr' => "<p>Réjouissez-vous ! Vous avez terminé le Nouveau Testament. Prenez le temps de célébrer ce que Dieu a révélé et réfléchissez à la façon dont ces lectures vous ont transformé au cours de l'année écoulée.</p>",
        'de' => '<p>Freue dich! Du hast das Neue Testament durchgelesen. Nimm dir Zeit zu feiern, was Gott offenbart hat, und überlege, wie dich die Lesungen im vergangenen Jahr geprägt haben.</p>',
        'it' => "<p>Rallegrati! Hai completato il Nuovo Testamento. Prenditi del tempo per celebrare ciò che Dio ti ha rivelato e rifletti su come le letture ti hanno plasmato nell'ultimo anno.</p>",
    ];

    public function run(): void
    {
        DB::transaction(function (): void {
            $plan = ReadingPlan::query()->updateOrCreate(
                ['slug' => self::SLUG],
                [
                    'name' => [
                        'en' => '5x5x5 New Testament Reading Plan',
                        'ro' => 'Plan de citire a Noului Testament 5x5x5',
                        'hu' => '5x5x5 újszövetségi olvasóterv',
                        'es' => 'Plan de lectura del Nuevo Testamento 5x5x5',
                        'fr' => 'Plan de lecture du Nouveau Testament 5x5x5',
                        'de' => '5x5x5 Leseplan für das Neue Testament',
                        'it' => 'Piano di lettura del Nuovo Testamento 5x5x5',
                    ],
                    'description' => [
                        'en' => 'Read through all 260 chapters of the New Testament in 5 days a week, 5 minutes a day. The Gospels are spaced throughout the year, and weekends are reserved for reflection.',
                        'ro' => 'Citește toate cele 260 de capitole ale Noului Testament în 5 zile pe săptămână, câte 5 minute pe zi. Evangheliile sunt răspândite pe parcursul anului, iar weekendurile sunt rezervate reflecției.',
                        'hu' => 'Olvasd át az Újszövetség mind a 260 fejezetét heti 5 napon, napi 5 perc alatt. Az evangéliumok egyenletesen oszlanak el az év során, a hétvégék pedig az elmélkedésé.',
                        'es' => 'Lee los 260 capítulos del Nuevo Testamento en 5 días a la semana, 5 minutos al día. Los Evangelios se distribuyen a lo largo del año y los fines de semana se reservan para la reflexión.',
                        'fr' => 'Lisez les 260 chapitres du Nouveau Testament en 5 jours par semaine, 5 minutes par jour. Les Évangiles sont répartis tout au long de l\'année et les week-ends sont consacrés à la réflexion.',
                        'de' => 'Lies alle 260 Kapitel des Neuen Testaments an 5 Tagen pro Woche in jeweils 5 Minuten. Die Evangelien sind über das Jahr verteilt, die Wochenenden sind der Besinnung gewidmet.',
                        'it' => 'Leggi tutti i 260 capitoli del Nuovo Testamento in 5 giorni alla settimana, 5 minuti al giorno. I Vangeli sono distribuiti nell\'arco dell\'anno e i weekend sono riservati alla riflessione.',
                    ],
                    'image' => [
                        'en' => 'https://placehold.co/1200x630?text=5x5x5+NT+Plan',
                        'ro' => 'https://placehold.co/1200x630?text=5x5x5+NT',
                        'hu' => 'https://placehold.co/1200x630?text=5x5x5+UT',
                        'es' => 'https://placehold.co/1200x630?text=5x5x5+NT',
                        'fr' => 'https://placehold.co/1200x630?text=5x5x5+NT',
                        'de' => 'https://placehold.co/1200x630?text=5x5x5+NT',
                        'it' => 'https://placehold.co/1200x630?text=5x5x5+NT',
                    ],
                    'thumbnail' => [
                        'en' => 'https://placehold.co/400x400?text=5x5x5',
                        'ro' => 'https://placehold.co/400x400?text=5x5x5',
                        'hu' => 'https://placehold.co/400x400?text=5x5x5',
                        'es' => 'https://placehold.co/400x400?text=5x5x5',
                        'fr' => 'https://placehold.co/400x400?text=5x5x5',
                        'de' => 'https://placehold.co/400x400?text=5x5x5',
                        'it' => 'https://placehold.co/400x400?text=5x5x5',
                    ],
                    'status' => ReadingPlanStatus::Published,
                    'published_at' => now(),
                ],
            );

            $plan->days()->delete();

            foreach (self::DAYS as $position => $entry) {
                $day = ReadingPlanDay::query()->create([
                    'reading_plan_id' => $plan->id,
                    'position' => $position,
                ]);

                match ($entry) {
                    'Reflection' => $this->seedHtmlFragment($day, self::REFLECTION_HTML),
                    'Rejoice!' => $this->seedHtmlFragment($day, self::REJOICE_HTML),
                    default => $this->seedReferenceFragments($day, $entry),
                };
            }
        });
    }

    /**
     * @param  array<string, string>  $content
     */
    private function seedHtmlFragment(ReadingPlanDay $day, array $content): void
    {
        ReadingPlanDayFragment::query()->create([
            'reading_plan_day_id' => $day->id,
            'position' => 1,
            'type' => FragmentType::Html,
            'content' => $content,
        ]);
    }

    /**
     * @var array<int, string>
     */
    private const DAYS = [
        1 => 'MRK.1',
        2 => 'MRK.2',
        3 => 'MRK.3',
        4 => 'MRK.4',
        5 => 'MRK.5',
        6 => 'Reflection',
        7 => 'Reflection',
        8 => 'MRK.6',
        9 => 'MRK.7',
        10 => 'MRK.8',
        11 => 'MRK.9',
        12 => 'MRK.10',
        13 => 'Reflection',
        14 => 'Reflection',
        15 => 'MRK.11',
        16 => 'MRK.12',
        17 => 'MRK.13',
        18 => 'MRK.14',
        19 => 'MRK.15',
        20 => 'Reflection',
        21 => 'Reflection',
        22 => 'MRK.16',
        23 => 'ACT.1',
        24 => 'ACT.2',
        25 => 'ACT.3',
        26 => 'ACT.4',
        27 => 'Reflection',
        28 => 'Reflection',
        29 => 'ACT.5',
        30 => 'ACT.6',
        31 => 'ACT.7',
        32 => 'ACT.8',
        33 => 'ACT.9',
        34 => 'Reflection',
        35 => 'Reflection',
        36 => 'ACT.10',
        37 => 'ACT.11',
        38 => 'ACT.12',
        39 => 'ACT.13',
        40 => 'ACT.14',
        41 => 'Reflection',
        42 => 'Reflection',
        43 => 'ACT.15',
        44 => 'ACT.16',
        45 => 'ACT.17',
        46 => 'ACT.18',
        47 => 'ACT.19',
        48 => 'Reflection',
        49 => 'Reflection',
        50 => 'ACT.20',
        51 => 'ACT.21',
        52 => 'ACT.22',
        53 => 'ACT.23',
        54 => 'ACT.24',
        55 => 'Reflection',
        56 => 'Reflection',
        57 => 'ACT.25',
        58 => 'ACT.26',
        59 => 'ACT.27',
        60 => 'ACT.28',
        61 => 'HEB.1',
        62 => 'Reflection',
        63 => 'Reflection',
        64 => 'HEB.2',
        65 => 'HEB.3',
        66 => 'HEB.4',
        67 => 'HEB.5',
        68 => 'HEB.6',
        69 => 'Reflection',
        70 => 'Reflection',
        71 => 'HEB.7',
        72 => 'HEB.8',
        73 => 'HEB.9',
        74 => 'HEB.10',
        75 => 'HEB.11',
        76 => 'Reflection',
        77 => 'Reflection',
        78 => 'HEB.12',
        79 => 'HEB.13',
        80 => 'GAL.1',
        81 => 'GAL.2',
        82 => 'GAL.3',
        83 => 'Reflection',
        84 => 'Reflection',
        85 => 'GAL.4',
        86 => 'GAL.5',
        87 => 'GAL.6',
        88 => 'JAS.1',
        89 => 'JAS.2',
        90 => 'Reflection',
        91 => 'Reflection',
        92 => 'JAS.3',
        93 => 'JAS.4',
        94 => 'JAS.5',
        95 => 'MAT.1',
        96 => 'MAT.2',
        97 => 'Reflection',
        98 => 'Reflection',
        99 => 'MAT.3',
        100 => 'MAT.4',
        101 => 'MAT.5',
        102 => 'MAT.6',
        103 => 'MAT.7',
        104 => 'Reflection',
        105 => 'Reflection',
        106 => 'MAT.8',
        107 => 'MAT.9',
        108 => 'MAT.10',
        109 => 'MAT.11',
        110 => 'MAT.12',
        111 => 'Reflection',
        112 => 'Reflection',
        113 => 'MAT.13',
        114 => 'MAT.14',
        115 => 'MAT.15',
        116 => 'MAT.16',
        117 => 'MAT.17',
        118 => 'Reflection',
        119 => 'Reflection',
        120 => 'MAT.18',
        121 => 'MAT.19',
        122 => 'MAT.20',
        123 => 'MAT.21',
        124 => 'MAT.22',
        125 => 'Reflection',
        126 => 'Reflection',
        127 => 'MAT.23',
        128 => 'MAT.24',
        129 => 'MAT.25',
        130 => 'MAT.26',
        131 => 'MAT.27',
        132 => 'Reflection',
        133 => 'Reflection',
        134 => 'MAT.28',
        135 => 'ROM.1',
        136 => 'ROM.2',
        137 => 'ROM.3',
        138 => 'ROM.4',
        139 => 'Reflection',
        140 => 'Reflection',
        141 => 'ROM.5',
        142 => 'ROM.6',
        143 => 'ROM.7',
        144 => 'ROM.8',
        145 => 'ROM.9',
        146 => 'Reflection',
        147 => 'Reflection',
        148 => 'ROM.10',
        149 => 'ROM.11',
        150 => 'ROM.12',
        151 => 'ROM.13',
        152 => 'ROM.14',
        153 => 'Reflection',
        154 => 'Reflection',
        155 => 'ROM.15',
        156 => 'ROM.16',
        157 => 'EPH.1',
        158 => 'EPH.2',
        159 => 'EPH.3',
        160 => 'Reflection',
        161 => 'Reflection',
        162 => 'EPH.4',
        163 => 'EPH.5',
        164 => 'EPH.6',
        165 => 'PHP.1',
        166 => 'PHP.2',
        167 => 'Reflection',
        168 => 'Reflection',
        169 => 'PHP.3',
        170 => 'PHP.4',
        171 => 'COL.1',
        172 => 'COL.2',
        173 => 'COL.3',
        174 => 'Reflection',
        175 => 'Reflection',
        176 => 'COL.4',
        177 => 'PHM.1',
        178 => 'LUK.1',
        179 => 'LUK.2',
        180 => 'LUK.3',
        181 => 'Reflection',
        182 => 'Reflection',
        183 => 'LUK.4',
        184 => 'LUK.5',
        185 => 'LUK.6',
        186 => 'LUK.7',
        187 => 'LUK.8',
        188 => 'Reflection',
        189 => 'Reflection',
        190 => 'LUK.9',
        191 => 'LUK.10',
        192 => 'LUK.11',
        193 => 'LUK.12',
        194 => 'LUK.13',
        195 => 'Reflection',
        196 => 'Reflection',
        197 => 'LUK.14',
        198 => 'LUK.15',
        199 => 'LUK.16',
        200 => 'LUK.17',
        201 => 'LUK.18',
        202 => 'Reflection',
        203 => 'Reflection',
        204 => 'LUK.19',
        205 => 'LUK.20',
        206 => 'LUK.21',
        207 => 'LUK.22',
        208 => 'LUK.23',
        209 => 'Reflection',
        210 => 'Reflection',
        211 => 'LUK.24',
        212 => '1CO.1',
        213 => '1CO.2',
        214 => '1CO.3',
        215 => '1CO.4',
        216 => 'Reflection',
        217 => 'Reflection',
        218 => '1CO.5',
        219 => '1CO.6',
        220 => '1CO.7',
        221 => '1CO.8',
        222 => '1CO.9',
        223 => 'Reflection',
        224 => 'Reflection',
        225 => '1CO.10',
        226 => '1CO.11',
        227 => '1CO.12',
        228 => '1CO.13',
        229 => '1CO.14',
        230 => 'Reflection',
        231 => 'Reflection',
        232 => '1CO.15',
        233 => '1CO.16',
        234 => '2CO.1',
        235 => '2CO.2',
        236 => '2CO.3',
        237 => 'Reflection',
        238 => 'Reflection',
        239 => '2CO.4',
        240 => '2CO.5',
        241 => '2CO.6',
        242 => '2CO.7',
        243 => '2CO.8',
        244 => 'Reflection',
        245 => 'Reflection',
        246 => '2CO.9',
        247 => '2CO.10',
        248 => '2CO.11',
        249 => '2CO.12',
        250 => '2CO.13',
        251 => 'Reflection',
        252 => 'Reflection',
        253 => '1TI.1',
        254 => '1TI.2',
        255 => '1TI.3',
        256 => '1TI.4',
        257 => '1TI.5',
        258 => 'Reflection',
        259 => 'Reflection',
        260 => '1TI.6',
        261 => '2TI.1',
        262 => '2TI.2',
        263 => '2TI.3',
        264 => '2TI.4',
        265 => 'Reflection',
        266 => 'Reflection',
        267 => 'TIT.1',
        268 => 'TIT.2',
        269 => 'TIT.3',
        270 => '1JN.1',
        271 => '1JN.2',
        272 => 'Reflection',
        273 => 'Reflection',
        274 => 'JN.3',
        275 => '1JN.4',
        276 => '1JN.5',
        277 => '2JN.1',
        278 => '3JN.1',
        279 => 'Reflection',
        280 => 'Reflection',
        281 => '1PE.1',
        282 => '1PE.2',
        283 => '1PE.3',
        284 => '1PE.4',
        285 => '1PE.5',
        286 => 'Reflection',
        287 => 'Reflection',
        288 => 'JHN.1',
        289 => 'JHN.2',
        290 => 'JHN.3',
        291 => 'JHN.4',
        292 => 'JHN.5',
        293 => 'Reflection',
        294 => 'Reflection',
        295 => 'JHN.6',
        296 => 'JHN.7',
        297 => 'JHN.8',
        298 => 'JHN.9',
        299 => 'JHN.10',
        300 => 'Reflection',
        301 => 'Reflection',
        302 => 'JHN.11',
        303 => 'JHN.12',
        304 => 'JHN.13',
        305 => 'JHN.14',
        306 => 'JHN.15',
        307 => 'Reflection',
        308 => 'Reflection',
        309 => 'JHN.16',
        310 => 'JHN.17',
        311 => 'JHN.18',
        312 => 'JHN.19',
        313 => 'JHN.20',
        314 => 'Reflection',
        315 => 'Reflection',
        316 => 'JHN.21',
        317 => '1TH.1',
        318 => '1TH.2',
        319 => '1TH.3',
        320 => '1TH.4',
        321 => 'Reflection',
        322 => 'Reflection',
        323 => '1TH.5',
        324 => '2TH.1',
        325 => '2TH.2',
        326 => '2TH.3',
        327 => '2PE.1',
        328 => 'Reflection',
        329 => 'Reflection',
        330 => '2PE.2',
        331 => '2PE.3',
        332 => 'JUD.1',
        333 => 'REV.1',
        334 => 'REV.2',
        335 => 'Reflection',
        336 => 'Reflection',
        337 => 'REV.3',
        338 => 'REV.4',
        339 => 'REV.5',
        340 => 'REV.6',
        341 => 'REV.7',
        342 => 'Reflection',
        343 => 'Reflection',
        344 => 'REV.8',
        345 => 'REV.9',
        346 => 'REV.10',
        347 => 'REV.11',
        348 => 'REV.12',
        349 => 'Reflection',
        350 => 'Reflection',
        351 => 'REV.13',
        352 => 'REV.14',
        353 => 'REV.15',
        354 => 'REV.16',
        355 => 'REV.17',
        356 => 'Reflection',
        357 => 'Reflection',
        358 => 'REV.18',
        359 => 'REV.19',
        360 => 'REV.20',
        361 => 'REV.21',
        362 => 'REV.22',
        363 => 'Reflection',
        364 => 'Reflection',
        365 => 'Rejoice!',
    ];
}
