[include]
files = /etc/supervisor/supervisord.conf

[program:npm]
process_name=%(program_name)s
command=/usr/local/bin/npm run dev -- --host 0.0.0.0
environment=ENABLE_NPM_FRONTEND=true
autostart=%(ENV_ENABLE_NPM_FRONTEND)s
autorestart=true
user=www-data
redirect_stderr=true
stopwaitsecs=60
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
